// ui/src/lib/components/report/Download.svelte
<script lang="ts">
	import DownloadIcon from '~icons/fa-solid/download'
	import ReplyAllIcon from '~icons/fa-solid/reply-all'
	import { API_HOST } from '$lib/env'
	import { Button } from '$lib/components/ui/button'
	import Job from './Job.svelte'

	type SubmitData = {
		uuid: string
		datasets: string
		field?: string
	}

	const { uuid, selectedAttribute, selectedDatasets, onCancel } = $props()
	let reportURL: string | null = $state(null)

	const data = $derived.by(() => {
		const submitData: SubmitData = {
			uuid,
			datasets: Object.entries(selectedDatasets)
				.filter(([_, v]) => v)
				.map(([k, _]) => k)
				.join(',')
		}
		if (selectedAttribute) {
			submitData.field = selectedAttribute
		}

		return submitData
	})

	const handleSuccess = (reportPath: string) => {
		const url = `${API_HOST}${reportPath}`
		reportURL = url

		window.location.href = url
	}

	$inspect('report URL', reportURL)
</script>

<div class="gap-8 sm:mt-12">
	{#if reportURL !== null}
		<div class="text-2xl font-bold">All done!</div>
		<p class="text-xl">
			Your report should download automatically. You can also click the button below to download
			your report.
		</p>

		<hr />

		<div class="flex gap-4 justify-between">
			<Button variant="destructive" onclick={onCancel}>
				<ReplyAllIcon class="size-6" />
				Start over
			</Button>

			<Button href={reportURL} target="_blank" class="no-underline">
				<DownloadIcon class="size-6" />
				Download report
			</Button>
		</div>
	{:else}
		<Job
			path="report"
			{data}
			defaultMessage="Creating report..."
			onSuccess={handleSuccess}
			{onCancel}
		/>
	{/if}
</div>

// ui/src/components/report/Download.jsx
import React, { useCallback, useState } from 'react'
import PropTypes from 'prop-types'
import { Box, Button, Flex, Divider, Paragraph, Text } from 'theme-ui'
import { ReplyAll, Download as DownloadIcon } from '@emotion-icons/fa-solid'

import { JobContainer } from 'components/job'
import { Link } from 'components/link'

import config from '../../../gatsby-config'

const { apiHost } = config.siteMetadata

const Download = ({ uuid, selectedAttribute, selectedDatasets, onCancel }) => {
  const [reportURL, setReportURL] = useState(null)

  const handleSuccess = useCallback((reportPath) => {
    const url = `${apiHost}${reportPath}`
    setReportURL(url)

    window.location.href = url
  }, [])

  if (reportURL !== null) {
    return (
      <Box>
        <Paragraph sx={{ fontSize: 4, pb: '2rem' }}>
          Your report should download automatically. You can also click the
          button below to download your report.
        </Paragraph>

        <Divider />

        <Flex sx={{ justifyContent: 'space-between' }}>
          <Button variant="primary" onClick={onCancel}>
            <Flex>
              <ReplyAll size="1.5em" style={{ marginRight: '0.5rem' }} />
              <Text>Start over</Text>
            </Flex>
          </Button>
          <Box>
            <Link href={reportURL} target="_blank">
              <Button variant="primary">
                <Flex>
                  <DownloadIcon
                    size="1.5em"
                    style={{ marginRight: '0.5rem' }}
                  />
                  <Text>Download report</Text>
                </Flex>
              </Button>
            </Link>
          </Box>
        </Flex>
      </Box>
    )
  }

  // failsafe to prevent submitting if no uuid
  if (uuid === null) {
    return null
  }

  const data = {
    uuid,
    datasets: selectedDatasets
      ? Object.entries(selectedDatasets)
          .filter(([_, v]) => v)
          .map(([k, _]) => k)
          .join(',')
      : '',
  }

  if (selectedAttribute) {
    data.field = selectedAttribute
  }

  return (
    <JobContainer
      path="report"
      data={data}
      defaultMessage="Creating report..."
      onSuccess={handleSuccess}
      onCancel={onCancel}
    />
  )
}

Download.propTypes = {
  uuid: PropTypes.string.isRequired,
  selectedAttribute: PropTypes.string,
  selectedDatasets: PropTypes.objectOf(PropTypes.bool).isRequired,
  onCancel: PropTypes.func.isRequired,
}

Download.defaultProps = {
  selectedAttribute: null,
}

export default Download
