// ui/src/lib/components/report/SelectDatasets.svelte
<script lang="ts">
	import CaretDown from '~icons/fa-solid/caret-down'
	import CaretRight from '~icons/fa-solid/caret-right'
	import { Badge } from '$lib/components/ui/badge'
	import { Button } from '$lib/components/ui/button'
	import { Checkbox } from '$lib/components/ui/checkbox'
	import * as Collapsible from '$lib/components/ui/collapsible'
	import { Label } from '$lib/components/ui/label'
	import { InfoTooltip } from '$lib/components/tooltip'
	import { cn } from '$lib/utils'

	import { categories } from '$lib/config/constants'
	import FreshwaterIcon from '$images/freshwater.svg'
	import CoastalIcon from '$images/coastal.svg'
	import LandIcon from '$images/land.svg'
	import TrendsIcon from '$images/trends.svg'

	const icons = {
		freshwater: FreshwaterIcon,
		coastal: CoastalIcon,
		land: LandIcon,
		trends: TrendsIcon
	}
	type IconIndex = 'freshwater' | 'coastal' | 'land' | 'trends'

	let {
		openCategories = $bindable(),
		availableDatasets,
		selectedDatasets = $bindable(),
		onBack,
		onNext
	} = $props()

	const handleSelectAll = () => {
		selectedDatasets = Object.fromEntries(
			Object.entries(availableDatasets).map(([id, isAvailable]) => [id, isAvailable])
		)
	}

	const handleSelectNone = () => {
		selectedDatasets = Object.fromEntries(
			Object.entries(selectedDatasets).map(([id]) => [id, false])
		)
	}

	const hasDatasets = $derived(Object.values(selectedDatasets).some((v) => v))
</script>

<div class="grid sm:grid-cols-[2fr_2fr] gap-8 sm:mt-12">
	<div>
		<div class="flex items-center gap-4">
			<Badge class="text-2xl size-9">3</Badge>
			<div class="text-2xl font-bold leading-tight">Select factors to include in report</div>
		</div>
		<p class="mt-4">
			This tool includes several standardized landscape-level datasets that help characterize
			different aspects of current and potential future conditions. Only those datasets that overlap
			with any of your analyis units are available for your analysis. Select any or all of these
			datasets on the right.
		</p>
	</div>
	<div>
		<div class="sm:flex justify-between gap-4">
			<div class="text-2xl font-bold">Available landscape-level factors:</div>
			<div class="flex items-center gap-2 flex-none justify-end">
				<Button variant="link" class="p-0" onclick={handleSelectAll}>select all</Button>
				<div class="text-grey-3">|</div>
				<Button variant="link" class=" p-0" onclick={handleSelectNone}>select none</Button>
			</div>
		</div>

		<div>
			{#each categories as category (category.id)}
				<Collapsible.Root
					bind:open={openCategories[category.id]}
					class="not-first-of-type:mt-2 not-last-of-type:mb-8"
				>
					<Collapsible.Trigger
						class="w-full py-2 border-t border-b items-center flex gap-2 text-start px-2 cursor-pointer"
						style={`background-color: ${category.color}; border-color: ${category.borderColor}`}
					>
						{#if openCategories[category.id]}
							<CaretDown class="size-6" />
						{:else}
							<CaretRight class="size-6" />
						{/if}
						<img
							src={icons[category.id as IconIndex]}
							alt={`${category.label} icon`}
							class="size-8"
						/>
						<div class="font-bold text-xl">
							{category.label}
						</div>
					</Collapsible.Trigger>
					<Collapsible.Content class="pt-4">
						{#each category.datasets as dataset (dataset.id)}
							<div class="flex items-center gap-2">
								<Checkbox
									id={dataset.id}
									class="cursor-pointer size-5 rounded-xs disabled:border-grey-4 border-2 [&_svg]:size-4"
									bind:checked={selectedDatasets[dataset.id]}
									disabled={!availableDatasets[dataset.id]}
								/>
								<Label
									for={dataset.id}
									class={cn('text-base cursor-pointer', {
										'italic opacity-100! text-grey-8 cursor-not-allowed':
											!availableDatasets[dataset.id]
									})}
									>{dataset.name}
									{#if !availableDatasets[dataset.id]}
										<span class="text-sm"> (no data available) </span>
									{/if}
								</Label>
								<InfoTooltip title={dataset.name} description={dataset.description} />
							</div>
						{/each}
					</Collapsible.Content>
				</Collapsible.Root>
			{/each}
		</div>

		<hr />

		<div class="flex justify-between gap-4">
			<Button variant="secondary" onclick={onBack}>Back</Button>
			<Button onclick={hasDatasets ? onNext : () => {}} disabled={!hasDatasets}
				>Create report</Button
			>
		</div>
	</div>
</div>

// ui/src/components/report/SelectDatasets.jsx
import React, { useCallback } from 'react'
import PropTypes from 'prop-types'
import {
  Box,
  Flex,
  Grid,
  Paragraph,
  Heading,
  Divider,
  Button,
  Text,
} from 'theme-ui'

import Category from './Category'

const SelectDatasets = ({
  categories,
  openCategories,
  availableDatasets,
  selectedDatasets,
  onToggleCategory,
  onToggleDatasets,
  onBack,
  onNext,
}) => {
  const handleSelectAll = useCallback(() => {
    onToggleDatasets(
      Object.keys(availableDatasets).reduce(
        (prev, id) => Object.assign(prev, { [id]: availableDatasets[id] }),
        {}
      )
    )
  }, [availableDatasets, onToggleDatasets])

  const handleSelectNone = useCallback(
    () => {
      onToggleDatasets(
        Object.keys(selectedDatasets).reduce(
          (prev, id) => Object.assign(prev, { [id]: false }),
          {}
        )
      )
    },
    // deliberately ignoring datasets since those don't change after mount
    [selectedDatasets, onToggleDatasets]
  )

  const hasDatasets =
    Object.values(selectedDatasets).filter((v) => v).length > 0

  return (
    <Grid columns={[0, 0, '1fr 2fr']} gap={5}>
      <Box>
        <Flex sx={{ alignItems: 'center', mb: '1rem' }}>
          <Box variant="boxes.step">3</Box>
          <Heading as="h1" sx={{ m: 0, fontSize: [3, 4] }}>
            Select factors to include in report
          </Heading>
        </Flex>
        <Paragraph>
          This tool includes several standardized landscape-level datasets that
          help characterize different aspects of current and potential future
          conditions. Only those datasets that overlap with any of your analyis
          units are available for your analysis. Select any or all of these
          datasets on the right.
        </Paragraph>
      </Box>
      <Box>
        <Flex sx={{ justifyContent: 'space-between', mb: '0.5rem' }}>
          <Heading as="h3" sx={{ m: 0 }}>
            Available landscape-level factors:
          </Heading>
          <Flex sx={{ alignItems: 'center', cursor: 'pointer', color: 'link' }}>
            <Text onClick={handleSelectAll} sx={{ fontSize: 0 }}>
              select all
            </Text>
            <Text
              onClick={handleSelectNone}
              sx={{
                fontSize: 0,
                ml: '0.5rem',
                pl: '0.5rem',
                borderLeft: '1px solid',
              }}
            >
              select none
            </Text>
          </Flex>
        </Flex>

        {categories.map((category) => (
          <Category
            key={category.id}
            {...category}
            datasets={category.datasets.map(({ id, ...rest }) => ({
              id,
              ...rest,
              selected: selectedDatasets[id],
              disabled: !availableDatasets[id],
            }))}
            isOpen={openCategories[category.id]}
            onToggle={onToggleCategory}
            onToggleDatasets={onToggleDatasets}
          />
        ))}

        <Divider />
        <Flex sx={{ justifyContent: 'space-between' }}>
          <Button as="button" variant="secondary" onClick={onBack}>
            Back
          </Button>

          {hasDatasets ? (
            <Button as="button" variant="primary" onClick={onNext}>
              Create report
            </Button>
          ) : (
            <Button as="button" variant="disabled" disabled>
              Create report
            </Button>
          )}
        </Flex>
      </Box>
    </Grid>
  )
}

SelectDatasets.propTypes = {
  categories: PropTypes.arrayOf(
    PropTypes.shape({
      id: PropTypes.string.isRequired,
      label: PropTypes.string.isRequired,
      color: PropTypes.string.isRequired,
      borderColor: PropTypes.string.isRequired,
      datasets: PropTypes.arrayOf(PropTypes.object).isRequired,
    })
  ).isRequired,
  openCategories: PropTypes.objectOf(PropTypes.bool).isRequired,
  availableDatasets: PropTypes.objectOf(PropTypes.bool).isRequired,
  selectedDatasets: PropTypes.objectOf(PropTypes.bool).isRequired,
  onToggleCategory: PropTypes.func.isRequired,
  onToggleDatasets: PropTypes.func.isRequired,
  onBack: PropTypes.func.isRequired,
  onNext: PropTypes.func.isRequired,
}

export default SelectDatasets
