// ui/src/lib/components/report/Upload.svelte
<script lang="ts">
	import Job from './Job.svelte'
	import UploadForm from './UploadForm.svelte'

	const { onSuccess } = $props()

	let data = $state(null)

	const handleSubmit = (newData) => {
		data = newData
	}

	const handleReset = () => {
		data = null
	}
</script>

<div class="text-lg sm:mt-12">
	{#if data !== null}
		<Job path="upload" {data} defaultMessage="Uploading..." {onSuccess} onCancel={handleReset} />
	{:else}
		<UploadForm onSubmit={handleSubmit} onReset={handleReset} />
	{/if}
</div>

// ui/src/components/report/Upload.jsx
import React, { useState } from 'react'
import PropTypes from 'prop-types'

import { JobContainer } from 'components/job'
import UploadForm from './UploadForm'

const Upload = ({ onSuccess }) => {
  const [data, setData] = useState(null)

  const handleSubmit = (newData) => {
    setData(() => newData)
  }

  const handleReset = () => {
    setData(() => null)
  }

  if (data !== null) {
    return (
      <JobContainer
        path="upload"
        data={data}
        defaultMessage="Uploading..."
        onSuccess={onSuccess}
        onCancel={handleReset}
      />
    )
  }

  return <UploadForm onSubmit={handleSubmit} onReset={handleReset} />
}

Upload.propTypes = {
  onSuccess: PropTypes.func.isRequired,
}

export default Upload
